---

- name: Check if nomad is installed
  stat:
    path: "/usr/local/bin/nomad"
  register: nomad_installed
  check_mode: no

- name: Get current nomad version
  shell: /usr/local/bin/nomad version | awk '$1 == "Nomad" {gsub(/^[a-z]+/, "", $NF); print $NF}'
  register: nomad_current_version
  check_mode: no
  when: nomad_installed.stat.exists

- name: Download nomad
  unarchive:
    src: "{{ nomad_url }}"
    dest: /usr/local/bin
    remote_src: yes
  when: (not nomad_installed.stat.exists) or (nomad_version is version_compare(nomad_current_version.stdout, '>'))

- name: Create nomad group
  group:
    name: "{{ nomad_group }}"

- name: Create nomad user
  user:
    name: "{{ nomad_user }}"
    groups: "{{ nomad_group }}"

- name: Install systemd unit
  template:
    src: nomad.service.j2
    dest: /etc/systemd/system/nomad.service
    owner: root
    group: root
    mode: 0640
  notify: start nomad

- name: Reread Systemd configs
  systemd: daemon_reload=yes

- name: Enable systemd unit
  systemd:
    name: nomad
    enabled: yes
    masked: no
